# Generated by Django 5.1.6 on 2025-03-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0002_rename_chatbot_chatbotresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotresponse",
            name="response_style",
            field=models.CharField(
                choices=[
                    ("CONCISE", "Resumida"),
                    ("NORMAL", "Normal"),
                    ("EXPLANATORY", "Extendida"),
                ],
                default="NORMAL",
                max_length=20,
                verbose_name="Estilo de respuesta",
            ),
        ),
    ]
